services:
  demo-target:
    build:
      context: ./scar-demo-target
    container_name: demo-target
    ports:
      - "5000:5000"
    networks:
      - scar-net
    restart: unless-stopped

  scar-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: scar-backend
    networks:
      - scar-net
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./nuclei-templates:/app/nuclei-templates
      - ./fallback-cache:/app/fallback-cache
    depends_on:
      - demo-target
    command: tail -f /dev/null
    restart: unless-stopped

networks:
  scar-net:
    driver: bridge
